version: '3.7'

services:
  auth:
    image: dnikolaidis/disastergram-auth
    build: .
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
    - "80:80"
    networks:
      - auth-net
    depends_on:
      - auth-db

  # https://hub.docker.com/_/postgres
  auth-db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    networks:
      - auth-net

networks:
  auth-net: